package model;

// Generated Apr 5, 2015 2:15:39 PM by Hibernate Tools 3.4.0.CR1

/**
 * Chitiethoadon generated by hbm2java
 */
public class Chitiethoadon implements java.io.Serializable {

	private Integer id;
	private Vattu vattu;
	private Hoadon hoadon;
	private int soluong;
	private float thue;
	private double thanhtien;
	private String ghichu;

	public Chitiethoadon() {
	}

	public Chitiethoadon(Vattu vattu, Hoadon hoadon, int soluong, float thue,
			double thanhtien) {
		this.vattu = vattu;
		this.hoadon = hoadon;
		this.soluong = soluong;
		this.thue = thue;
		this.thanhtien = thanhtien;
	}

	public Chitiethoadon(Vattu vattu, Hoadon hoadon, int soluong, float thue,
			double thanhtien, String ghichu) {
		this.vattu = vattu;
		this.hoadon = hoadon;
		this.soluong = soluong;
		this.thue = thue;
		this.thanhtien = thanhtien;
		this.ghichu = ghichu;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Vattu getVattu() {
		return this.vattu;
	}

	public void setVattu(Vattu vattu) {
		this.vattu = vattu;
	}

	public Hoadon getHoadon() {
		return this.hoadon;
	}

	public void setHoadon(Hoadon hoadon) {
		this.hoadon = hoadon;
	}

	public int getSoluong() {
		return this.soluong;
	}

	public void setSoluong(int soluong) {
		this.soluong = soluong;
	}

	public float getThue() {
		return this.thue;
	}

	public void setThue(float thue) {
		this.thue = thue;
	}

	public double getThanhtien() {
		return this.thanhtien;
	}

	public void setThanhtien(double thanhtien) {
		this.thanhtien = thanhtien;
	}

	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((vattu == null) ? 0 : vattu.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Chitiethoadon other = (Chitiethoadon) obj;
		if (vattu == null) {
			if (other.vattu != null)
				return false;
		} else if (!vattu.getMavattu().equals(other.vattu.getMavattu()))
			return false;
		return true;
	}

	

	
	
	
}
