package model;

// Generated Apr 5, 2015 2:15:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Doituong generated by hbm2java
 */
public class Doituong implements java.io.Serializable {

	private Integer id;
	private String madoituong;
	private String tendoituong;
	private String diachi;
	private Set<Hoadon> hoadons = new HashSet<Hoadon>(0);

	public Doituong() {
	}

	public Doituong(String madoituong, String tendoituong, String diachi) {
		this.madoituong = madoituong;
		this.tendoituong = tendoituong;
		this.diachi = diachi;
	}

	public Doituong(String madoituong, String tendoituong, String diachi,
			Set<Hoadon> hoadons) {
		this.madoituong = madoituong;
		this.tendoituong = tendoituong;
		this.diachi = diachi;
		this.hoadons = hoadons;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getMadoituong() {
		return this.madoituong;
	}

	public void setMadoituong(String madoituong) {
		this.madoituong = madoituong;
	}

	public String getTendoituong() {
		return this.tendoituong;
	}

	public void setTendoituong(String tendoituong) {
		this.tendoituong = tendoituong;
	}

	public String getDiachi() {
		return this.diachi;
	}

	public void setDiachi(String diachi) {
		this.diachi = diachi;
	}

	public Set<Hoadon> getHoadons() {
		return this.hoadons;
	}

	public void setHoadons(Set<Hoadon> hoadons) {
		this.hoadons = hoadons;
	}

	@Override
	public String toString() {
		return tendoituong ;
	}
	
	

}
