package model;

// Generated Apr 5, 2015 2:15:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Hoadon generated by hbm2java
 */
public class Hoadon implements java.io.Serializable {

	private Integer id;
	private Kho kho;
	private User user;
	private Nhacungcap nhacungcap;
	private Doituong doituong;
	private Date ngay;
	private String sochungtu;
	private Integer sohoadon;
	private String loaihoadon;
	private String thanhtoan;
	private String nguoinhan;
	private String ghichu;
	private Set<Chitiethoadon> chitiethoadons = new HashSet<Chitiethoadon>(0);

	public Hoadon() {
	}

	public Hoadon(Kho kho, User user, Nhacungcap nhacungcap, Doituong doituong,
			Date ngay, String sochungtu, String loaihoadon, String thanhtoan) {
		this.kho = kho;
		this.user = user;
		this.nhacungcap = nhacungcap;
		this.doituong = doituong;
		this.ngay = ngay;
		this.sochungtu = sochungtu;
		this.loaihoadon = loaihoadon;
		this.thanhtoan = thanhtoan;
	}

	public Hoadon(Kho kho, User user, Nhacungcap nhacungcap, Doituong doituong,
			Date ngay, String sochungtu, Integer sohoadon, String loaihoadon,
			String thanhtoan, String nguoinhan, String ghichu,
			Set<Chitiethoadon> chitiethoadons) {
		this.kho = kho;
		this.user = user;
		this.nhacungcap = nhacungcap;
		this.doituong = doituong;
		this.ngay = ngay;
		this.sochungtu = sochungtu;
		this.sohoadon = sohoadon;
		this.loaihoadon = loaihoadon;
		this.thanhtoan = thanhtoan;
		this.nguoinhan = nguoinhan;
		this.ghichu = ghichu;
		this.chitiethoadons = chitiethoadons;
	}
	
	

	public Hoadon(Kho kho, User user, Nhacungcap nhacungcap, Doituong doituong,
			Date ngay, String sochungtu, Integer sohoadon, String loaihoadon,
			String thanhtoan, String nguoinhan, String ghichu) {
		super();
		this.kho = kho;
		this.user = user;
		this.nhacungcap = nhacungcap;
		this.doituong = doituong;
		this.ngay = ngay;
		this.sochungtu = sochungtu;
		this.sohoadon = sohoadon;
		this.loaihoadon = loaihoadon;
		this.thanhtoan = thanhtoan;
		this.nguoinhan = nguoinhan;
		this.ghichu = ghichu;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Kho getKho() {
		return this.kho;
	}

	public void setKho(Kho kho) {
		this.kho = kho;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Nhacungcap getNhacungcap() {
		return this.nhacungcap;
	}

	public void setNhacungcap(Nhacungcap nhacungcap) {
		this.nhacungcap = nhacungcap;
	}

	public Doituong getDoituong() {
		return this.doituong;
	}

	public void setDoituong(Doituong doituong) {
		this.doituong = doituong;
	}

	public Date getNgay() {
		return this.ngay;
	}

	public void setNgay(Date ngay) {
		this.ngay = ngay;
	}

	public String getSochungtu() {
		return this.sochungtu;
	}

	public void setSochungtu(String sochungtu) {
		this.sochungtu = sochungtu;
	}

	public Integer getSohoadon() {
		return this.sohoadon;
	}

	public void setSohoadon(Integer sohoadon) {
		this.sohoadon = sohoadon;
	}

	public String getLoaihoadon() {
		return this.loaihoadon;
	}

	public void setLoaihoadon(String loaihoadon) {
		this.loaihoadon = loaihoadon;
	}

	public String getThanhtoan() {
		return this.thanhtoan;
	}

	public void setThanhtoan(String thanhtoan) {
		this.thanhtoan = thanhtoan;
	}

	public String getNguoinhan() {
		return this.nguoinhan;
	}

	public void setNguoinhan(String nguoinhan) {
		this.nguoinhan = nguoinhan;
	}

	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

	public Set<Chitiethoadon> getChitiethoadons() {
		return this.chitiethoadons;
	}

	public void setChitiethoadons(Set<Chitiethoadon> chitiethoadons) {
		this.chitiethoadons = chitiethoadons;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((sochungtu == null) ? 0 : sochungtu.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Hoadon other = (Hoadon) obj;
		if (sochungtu == null) {
			if (other.sochungtu != null)
				return false;
		} else if (!sochungtu.equals(other.sochungtu))
			return false;
		return true;
	}

	
	

}
