package model;

// Generated Apr 5, 2015 2:15:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Nhacungcap generated by hbm2java
 */
public class Nhacungcap implements java.io.Serializable {

	private Integer id;
	private String manhacungcap;
	private String tennhacungcap;
	private String diachi;
	private Set<Hoadon> hoadons = new HashSet<Hoadon>(0);

	public Nhacungcap() {
	}

	public Nhacungcap(String manhacungcap, String tennhacungcap, String diachi) {
		this.manhacungcap = manhacungcap;
		this.tennhacungcap = tennhacungcap;
		this.diachi = diachi;
	}

	public Nhacungcap(String manhacungcap, String tennhacungcap, String diachi,
			Set<Hoadon> hoadons) {
		this.manhacungcap = manhacungcap;
		this.tennhacungcap = tennhacungcap;
		this.diachi = diachi;
		this.hoadons = hoadons;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getManhacungcap() {
		return this.manhacungcap;
	}

	public void setManhacungcap(String manhacungcap) {
		this.manhacungcap = manhacungcap;
	}

	public String getTennhacungcap() {
		return this.tennhacungcap;
	}

	public void setTennhacungcap(String tennhacungcap) {
		this.tennhacungcap = tennhacungcap;
	}

	public String getDiachi() {
		return this.diachi;
	}

	public void setDiachi(String diachi) {
		this.diachi = diachi;
	}

	public Set<Hoadon> getHoadons() {
		return this.hoadons;
	}

	public void setHoadons(Set<Hoadon> hoadons) {
		this.hoadons = hoadons;
	}

	@Override
	public String toString() {
		return  tennhacungcap ;
	}
	
	

}
