package model;

// Generated Apr 5, 2015 2:15:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Nhacungcap generated by hbm2java
 */
public class Nhacungcap implements java.io.Serializable {

	private Integer id;
	private String manhacungcap;
	private String tennhacungcap;
	private String diachi;
	private Set<Hoadon> hoadons = new HashSet<Hoadon>(0);

	public Nhacungcap() {
	}

	public Nhacungcap(String manhacungcap, String tennhacungcap, String diachi) {
		this.manhacungcap = manhacungcap;
		this.tennhacungcap = tennhacungcap;
		this.diachi = diachi;
	}

	public Nhacungcap(String manhacungcap, String tennhacungcap, String diachi,
			Set<Hoadon> hoadons) {
		this.manhacungcap = manhacungcap;
		this.tennhacungcap = tennhacungcap;
		this.diachi = diachi;
		this.hoadons = hoadons;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getManhacungcap() {
		return this.manhacungcap;
	}

	public void setManhacungcap(String manhacungcap) {
		this.manhacungcap = manhacungcap;
	}

	public String getTennhacungcap() {
		return this.tennhacungcap;
	}

	public void setTennhacungcap(String tennhacungcap) {
		this.tennhacungcap = tennhacungcap;
	}

	public String getDiachi() {
		return this.diachi;
	}

	public void setDiachi(String diachi) {
		this.diachi = diachi;
	}

	public Set<Hoadon> getHoadons() {
		return this.hoadons;
	}

	public void setHoadons(Set<Hoadon> hoadons) {
		this.hoadons = hoadons;
	}

	@Override
	public String toString() {
		return  tennhacungcap ;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((manhacungcap == null) ? 0 : manhacungcap.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Nhacungcap other = (Nhacungcap) obj;
		if (manhacungcap == null) {
			if (other.manhacungcap != null)
				return false;
		} else if (!manhacungcap.equals(other.manhacungcap))
			return false;
		return true;
	}
	
	

}
